name: Automated Build

on:
  push:
    paths:
      - 'CHANGELOG.md'
      - '.github\workflows\build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches
    
    - name: Set up PlatformIO
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install platformio
    
    - name: Install git-semver
      run: |
        npm install -g git-semver
        echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Calculate version
      id: semver
      run: echo "version=$(git-semver)" >> $GITHUB_OUTPUT
    
    - name: Build project
      run: platformio run
    
    - name: Update CHANGELOG.md
      run: |
        sed -i "s/## \[Unreleased\]/## [${{ steps.semver.outputs.version }}] - $(date +'%Y-%m-%d')/" CHANGELOG.md
    
    - name: Get latest changelog entry
      id: changelog
      run: |
        LATEST_ENTRY=$(sed -n '/^## /,/^## /p' CHANGELOG.md | sed '$d' | tail -n +2)
        echo "latest_entry=$LATEST_ENTRY" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.semver.outputs.version }}
        release_name: Release v${{ steps.semver.outputs.version }}
        body: ${{ steps.changelog.outputs.latest_entry }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./.pio/build/esp32doit-devkit-v1/firmware.bin
        tag_name: v${{ steps.semver.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit CHANGELOG.md changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update CHANGELOG.md for version ${{ steps.semver.outputs.version }}"
        git push
